Repository Team-INSERT/bssm-frontend, pull requests merged in 2023-09, with the labels that each got.

#60 대나무숲 API 연동 완료
  package.json
  src/apis/error/throwAxiosError.ts
  src/apis/httpClient/httpClient.ts
  src/apis/interceptor/index.ts
  src/app/layout.tsx
  src/app/registry.tsx
  src/components/atoms/ImageWithFallback.tsx
  src/components/common/Aside/InfomationBox.tsx
  src/components/common/Modal/BambooCreateModal/index.tsx
  src/components/common/Modal/BambooManageModal/BambooFilter.tsx
  src/components/common/Modal/BambooManageModal/BambooManagePostListItem.tsx
  src/components/common/Modal/BambooManageModal/index.tsx
  src/components/common/Modal/ConfirmModal/index.tsx
  src/constants/key.constant.ts
  src/constants/role.constant.ts
  src/helpers/index.ts
  src/helpers/isAdmin.helper.ts
  src/hooks/useDate.ts
  src/interfaces/bambooPendingPost.interface.ts
  src/interfaces/bambooPost.interface.ts
  src/interfaces/index.ts
  src/libs/index.ts
  src/libs/useApolloQuery.ts
  src/page/bamboo/index.tsx
  src/page/bamboo/layouts/BambooPostList.tsx
  src/page/bamboo/layouts/BambooPostListItem.tsx
  src/page/bamboo/services/api.service.ts
  src/page/bamboo/services/mutation.service.ts
  src/page/bamboo/services/query.service.ts
  src/page/forum-post/layouts/Post.tsx
  src/page/forum/layouts/Forum.tsx
  src/page/forum/layouts/PostListItem.tsx
  src/page/oauth/index.tsx
  src/page/oauth/services/mutation.service.ts
  src/page/timetable/layouts/TimeTableBox.tsx
  src/page/timetable/services/query.service.ts
  src/provider/apolloClientProvider.helper.tsx
  src/provider/layoutProvider.helper.tsx
  src/provider/provider.helper.tsx
  src/provider/reactQueryProvider.helper.tsx
  yarn.lock
Labels: enhancement, refactor

#61 chore(pagenation): 무한스크롤 구현
  src/page/bamboo/layouts/BambooPostList.tsx
  src/page/bamboo/services/query.service.ts
Labels: enhancement

#62 post 페이지네이션(무한스크롤) 적용
  src/constants/router.constant.ts
  src/gql/post/data.ts
  src/gql/post/queries.ts
  src/helpers/getCategory.helper.ts
  src/helpers/getPageSize.helper.ts
  src/interfaces/index.ts
  src/interfaces/infiniteResult.interface.ts
  src/interfaces/postInfiniteList.interface.ts
  src/page/forum-post/layouts/Post.tsx
  src/page/forum-post/layouts/PostHead/Category.tsx
  src/page/forum-post/layouts/PostHead/PostTitle.tsx
  src/page/forum-post/layouts/PostHead/index.tsx
  src/page/forum-post/services/query.service.ts
  src/page/forum/layouts/Forum.tsx
  src/page/forum/layouts/PostList.tsx
  src/page/forum/services/query.service.ts
Labels: enhancement, refactor

#63 post 페이지 좋아요 개수, 댓글 개수, 유저 정보 연동 완료
  src/components/atoms/ImageWithFallback.tsx
  src/fixture/post.ts
  src/fixture/postList.ts
  src/gql/post/data.ts
  src/interfaces/post.interface.ts
  src/page/forum-post/layouts/PostBody/CountBox.tsx
  src/page/forum-post/layouts/PostBody/index.tsx
  src/page/forum-post/layouts/PostHead/PostTitle.tsx
  src/page/forum-post/layouts/PostHead/ReactBox.tsx
  src/page/forum/layouts/PostListItem.tsx
  src/page/lostfound-post/layouts/LostFoundBody/index.tsx
  src/page/lostfound/layouts/LostFoundListItem.tsx
Labels: refactor

#64 feat : 좋아요 버튼
  src/page/forum-post/layouts/PostBody/CountBox.tsx
Labels: enhancement

#65 좋아요 API 연결을 완료했습니다.
  src/apis/httpClient/httpClient.ts
  src/assets/icons/LikeIcon.tsx
  src/constants/index.ts
  src/constants/likeType.constant.ts
  src/fixture/post.ts
  src/fixture/postList.ts
  src/interfaces/post.interface.ts
  src/page/forum-post/layouts/PostBody/CountBox.tsx
Labels: enhancement

#76 Post 답글 기능 구현
  src/apis/httpClient/httpClient.ts
  src/constants/key.constant.ts
  src/helpers/checkTextOverflow.helper.ts
  src/helpers/getTextDepth.helper.ts
  src/helpers/index.ts
  src/hooks/useTextarea.ts
  src/interfaces/index.ts
  src/interfaces/recomment.interface.ts
  src/page/forum-post/layouts/PostBody/Comment/CommentList.tsx
  src/page/forum-post/layouts/PostBody/Comment/CommentListItem.tsx
  src/page/forum-post/layouts/PostBody/Comment/CreateCommentBox.tsx
  src/page/forum-post/layouts/PostBody/Recomment/CreateRecommentBox.tsx
  src/page/forum-post/layouts/PostBody/Recomment/RecommentList.tsx
  src/page/forum-post/layouts/PostBody/Recomment/RecommentListItem.tsx
  src/page/forum-post/layouts/PostBody/index.tsx
  src/page/forum-post/services/api.service.ts
  src/page/forum-post/services/mutation.service.ts
  src/page/forum-post/services/query.service.ts
Labels: enhancement

#77 스타일드 컴포넌트 SSR 이슈 해결
  src/app/layout.tsx
  src/provider/ServerStyleProvider.tsx
  src/provider/StyledComponentsProvider.helper.tsx
  src/provider/provider.helper.tsx
Labels: enhancement

#79 깃 이슈로 인해 임시 프로바이더 삭제
  src/app/layout.tsx
  src/provider/ServerStyleProvider.tsx
  src/provider/StyledComponentsProvider.helper.tsx
  src/provider/apolloClientProvider.helper.tsx
  src/provider/layoutProvider.helper.tsx
  src/provider/provider.helper.tsx
  src/provider/reactQueryProvider.helper.tsx
Labels: bug
