Repository Team-INSERT/bssm-frontend, pull requests merged in 2023-08, with the labels that each got.

#43 이모티콘 모달 추가
  next.config.js
  src/components/atoms/CommentBox.tsx
  src/components/atoms/CustomEditor.tsx
  src/components/common/Header/Navigation.tsx
  src/components/common/Header/index.tsx
  src/components/common/Modal/EmojiModal/ModalHeader.tsx
  src/components/common/Modal/EmojiModal/ModalList.tsx
  src/components/common/Modal/EmojiModal/ModalListItem.tsx
  src/components/common/Modal/EmojiModal/index.tsx
  src/components/common/Modal/View.tsx
  src/global/assets/icons/emoticon.png
  src/global/assets/svgs/Emoji.tsx
  src/global/assets/svgs/XIcon.tsx
  src/global/assets/svgs/emojis/Grinning.tsx
  src/global/assets/svgs/emojis/HoldingBackTears.tsx
  src/global/assets/svgs/emojis/Kissing.tsx
  src/global/assets/svgs/emojis/Laughing.tsx
  src/global/assets/svgs/emojis/Relaxed.tsx
  src/global/assets/svgs/emojis/StyledEmoji.tsx
  src/global/types/SVGAttribute.type.ts
  src/global/types/emoji.type.ts
  src/hooks/useEmoji.ts
  src/page/calender/layouts/ScheduleBox.tsx
  src/page/forum-post/assets/Emoji.tsx
  src/page/forum-post/layouts/Post.tsx
  src/page/forum-post/layouts/PostBody/index.tsx
  src/page/forum-write/layouts/WriteBox.tsx
  src/page/forum/layouts/Forum.tsx
  src/page/lostfound-post/layouts/LostFoundBody/CommentBox.tsx
  src/page/lostfound-post/layouts/LostFoundBody/index.tsx
  src/page/lostfound-post/layouts/LostFoundPostBox.tsx
  src/page/lostfound-write/index.tsx
  src/page/lostfound-write/layouts/LostFoundWriteBox.tsx
  src/page/lostfound/layouts/LostFoundBox.tsx
  src/page/meal/layouts/ListSlider.tsx
  src/page/meal/layouts/MealListItem.tsx
  src/page/meal/types/mealList.type.ts
  src/page/meal/types/mealListItem.type.ts
  src/page/timetable/layouts/TimeTableBox.tsx
  src/styles/color.ts
Labels: bug, enhancement, refactor

#47 마이스터 역량 인증제 페이지 퍼블리싱
  next.config.js
  package.json
  radar.d.ts
  src/app/bamboo/page.tsx
  src/app/meister/page.tsx
  src/assets/icons/Curve.tsx
  src/assets/icons/DistributionIcon.tsx
  src/assets/icons/GraphIcon.tsx
  src/assets/icons/HistorySeparator.tsx
  src/assets/icons/ProgressIcon.tsx
  src/assets/icons/index.ts
  src/components/atoms/ImageWithFallback.tsx
  src/helpers/getStatusColor.helper.ts
  src/helpers/index.ts
  src/hooks/useDate.ts
  src/page/bamboo/index.tsx
  src/page/meister/chart/MeisterChart.tsx
  src/page/meister/chart/RadarChart.tsx
  src/page/meister/index.tsx
  src/page/meister/layouts/CreditDemeritCard.tsx
  src/page/meister/layouts/Distribution.tsx
  src/page/meister/layouts/HistoryCard.tsx
  src/page/meister/layouts/MeisterProfileBox.tsx
  src/page/meister/layouts/StatusCard.tsx
  src/page/meister/layouts/YearlyMeisterScore.tsx
  src/styles/color.ts
  src/styles/flex.ts
  yarn.lock
Labels: enhancement

#53 베르실 예약 페이지 퍼블리싱
  src/app/reserve/page.tsx
  src/assets/icons/CheckIcon.tsx
  src/components/atoms/Input.tsx
  src/page/meister/index.tsx
  src/page/reserve/index.tsx
  src/page/reserve/layouts/ReserveBox.tsx
  src/page/reserve/layouts/ReserveJoinBox.tsx
  src/page/reserve/layouts/ReserveMap.tsx
Labels: enhancement

#54 Apollo 세팅
  package.json
  src/helpers/apoloClientProvider.helper.tsx
  src/helpers/provider.helper.tsx
  src/libs/index.ts
  src/libs/useApolloQuery.ts
  yarn.lock
Labels: enhancement

#55 build: appspec.yml
  appspec.yml
Labels: enhancement

#57 유저 DTO 변경, Bearer 토큰으로 API 통신 방식 변경
  src/apis/httpClient/httpClient.ts
  src/apis/storage/index.ts
  src/apis/token/index.ts
  src/apis/token/refresh.ts
  src/apis/token/request.ts
  src/components/common/Aside/InfomationBox.tsx
  src/helpers/layoutProvider.helper.tsx
  src/hooks/useDate.ts
  src/interfaces/index.ts
  src/interfaces/user.interface.ts
  src/store/user.store.ts
  src/styles/globals.css
  src/styles/index.ts
  src/styles/style.ts
Labels: refactor

#59 게시판 로직 완성, 유저 인증 도메인 수정
  src/apis/httpClient/httpClient.ts
  src/apis/token/authorization.ts
  src/apis/token/index.ts
  src/apis/token/refresh.ts
  src/apis/token/request.ts
  src/app/post/[id]/page.tsx
  src/assets/data/emptyCategories.ts
  src/components/atoms/ImageWithFallback.tsx
  src/constants/forum.constant.ts
  src/constants/index.ts
  src/constants/post.constant.ts
  src/fixture/post.ts
  src/fixture/postList.ts
  src/gql/post/data.ts
  src/gql/post/queries.ts
  src/helpers/apolloClientProvider.helper.tsx
  src/helpers/getPostType.helper.ts
  src/helpers/getProfileUrl.helper.ts
  src/helpers/index.ts
  src/helpers/provider.helper.tsx
  src/hooks/useTimetableBar.ts
  src/hooks/useUser.ts
  src/interfaces/index.ts
  src/interfaces/postListQuery.interface.ts
  src/interfaces/postQuery.interface.ts
  src/page/bamboo/services/api.service.ts
  src/page/forum-post/index.tsx
  src/page/forum-post/layouts/Post.tsx
  src/page/forum-post/layouts/PostHead/Category.tsx
  src/page/forum-post/layouts/PostHead/PostTitle.tsx
  src/page/forum-post/services/api.service.ts
  src/page/forum-post/services/query.service.ts
  src/page/forum/layouts/Forum.tsx
  src/page/forum/layouts/ForumFilter.tsx
  src/page/forum/layouts/PostListItem.tsx
  src/page/forum/services/api.service.ts
  src/page/forum/services/query.service.ts
  src/page/oauth/index.tsx
  src/page/oauth/services/mutations.service.ts
  src/page/timetable/layouts/TimeTableBar.tsx
  src/store/categories.store.ts
  src/store/forumFilter.store.ts
  src/types/postCategory.type.ts
Labels: bug, enhancement, refactor
