Repository Team-INSERT/bssm-frontend, pull requests merged in 2023-11, with the labels that each got.

#98 QA, 버그 픽스
  next.config.js
  src/app/layout.tsx
  src/app/not-found.tsx
  src/assets/icons/Arrow.tsx
  src/assets/icons/Logo.tsx
  src/assets/images/index.ts
  src/assets/images/page_not_found.png
  src/components/common/Aside/InfomationBox.tsx
  src/components/common/Header/Navigation.tsx
  src/components/common/Header/SubNavigation.tsx
  src/components/common/Header/index.tsx
  src/components/common/Modal/EmojiModal/index.tsx
  src/components/common/Modal/LoginModal/index.tsx
  src/components/common/Modal/PlanAddModal/index.tsx
  src/components/common/Modal/SettingModal/SettingBody.tsx
  src/components/common/Modal/SettingModal/index.tsx
  src/constants/token.constant.ts
  src/helpers/checkPostValid.helper.ts
  src/helpers/getPlanType.helper.ts
  src/hooks/useMeisterHTML.ts
  src/hooks/useTimetableBar.ts
  src/provider/layoutProvider.helper.tsx
  src/store/searchStudentNumber.store.ts
  src/templates/calender/layouts/CalenderList.tsx
  src/templates/calender/layouts/CalenderListItem.tsx
  src/templates/calender/layouts/ScheduleBox.tsx
  src/templates/forum-post/layouts/PostBody/Comment/CreateCommentBox.tsx
  src/templates/forum-post/layouts/PostBody/Recomment/CreateRecommentBox.tsx
  src/templates/forum-post/services/mutation.service.ts
  src/templates/forum-post/services/query.service.ts
  src/templates/forum/layouts/Forum.tsx
  src/templates/home/index.tsx
  src/templates/home/layouts/HomeReserve.tsx
  src/templates/home/layouts/HomeReserveMap.tsx
  src/templates/meal/index.tsx
  src/templates/meal/layouts/MealListItem.tsx
  src/templates/meister/index.tsx
  src/templates/meister/layouts/MeisterProfileBox.tsx
  src/templates/meister/services/api.service.ts
  src/templates/meister/services/query.service.ts
  src/templates/oauth/services/mutation.service.ts
  src/templates/reserve/services/mutation.service.ts
  src/templates/timetable/index.tsx
  src/templates/timetable/layouts/TimeTableBar.tsx
  src/templates/timetable/layouts/TimeTableBox.tsx
  src/templates/timetable/layouts/TimeTableCategory.tsx
  src/templates/timetable/layouts/TimeTableTable.tsx
  src/types/storageSettingKey.type.ts
Labels: bug, refactor

#99 홈 레이아웃에 API를 연결하고 버그를 수정했습니다.
  src/components/common/Aside/InfomationBox.tsx
  src/components/common/Aside/MeisterBox.tsx
  src/constants/key.constant.ts
  src/hooks/useMeal.ts
  src/hooks/useMeister.ts
  src/store/meister.store.ts
  src/templates/home/index.tsx
  src/templates/home/layouts/HomeBamboo.tsx
  src/templates/home/layouts/HomeCalender.tsx
  src/templates/home/layouts/HomeMeal.tsx
  src/templates/home/layouts/HomeMiniBanner.tsx
  src/templates/home/layouts/HomePost.tsx
  src/templates/home/layouts/HomePostList.tsx
Labels: bug

#100 Fix/chore
  src/hooks/useMeisterHTML.ts
  src/templates/home/layouts/HomeCalender.tsx
  src/templates/meister/index.tsx
Labels: bug

#101 home remocon 모드 추가
  src/assets/icons/BerIcon.tsx
  src/assets/icons/CalenderIcon.tsx
  src/assets/icons/JoinCheckIcon.tsx
  src/assets/icons/MealIcon.tsx
  src/assets/icons/NoticeIcon.tsx
  src/assets/icons/TimetableIcon.tsx
  src/constants/router.constant.ts
  src/hooks/useDate.ts
  src/hooks/useMeal.ts
  src/templates/home/index.tsx
  src/templates/home/layouts/BasicMode/HomeBamboo.tsx
  src/templates/home/layouts/BasicMode/HomeCalender.tsx
  src/templates/home/layouts/BasicMode/HomeHead.tsx
  src/templates/home/layouts/BasicMode/HomeMainBanner.tsx
  src/templates/home/layouts/BasicMode/HomeMeal.tsx
  src/templates/home/layouts/BasicMode/HomeMiniBanner.tsx
  src/templates/home/layouts/BasicMode/HomePost.tsx
  src/templates/home/layouts/BasicMode/HomePostList.tsx
  src/templates/home/layouts/BasicMode/HomeRadarChart.tsx
  src/templates/home/layouts/BasicMode/HomeReserve.tsx
  src/templates/home/layouts/BasicMode/HomeReserveMap.tsx
  src/templates/home/layouts/BasicMode/index.tsx
  src/templates/home/layouts/RemoconMode/index.tsx
  src/types/storageSettingKey.type.ts
Labels: enhancement

#102 로그인안되어있으면 모달 수정
  src/templates/home/layouts/BasicMode/index.tsx
Labels: bug

#114 베르실 예약 페이지 리팩토링
  src/apis/httpClient/httpClient.ts
  src/app/ber/page.tsx
  src/app/reserve/page.tsx
  src/assets/data/index.ts
  src/assets/icons/CalendarIcon.tsx
  src/components/atoms/Input.tsx
  src/interfaces/reserveList.interface.ts
  src/store/reserveViewType.store.ts
  src/templates/ber/assets/data/berReserveData.ts
  src/templates/ber/assets/data/index.ts
  src/templates/ber/assets/data/noticeRuleList.ts
  src/templates/ber/assets/icons/BerReserveCloseIcon.tsx
  src/templates/ber/assets/icons/index.ts
  src/templates/ber/constants/ber.constant.ts
  src/templates/ber/constants/index.ts
  src/templates/ber/helpers/getIfReservedRoomCSS.helper.ts
  src/templates/ber/helpers/getIfSelectedRoomCSS.helper.ts
  src/templates/ber/helpers/index.ts
  src/templates/ber/hooks/index.ts
  src/templates/ber/hooks/useBer.ts
  src/templates/ber/hooks/useBerReserve.ts
  src/templates/ber/interfaces/@props/berReserveCheckBoxProps.interface.ts
  src/templates/ber/interfaces/@props/berReserveJoinBoxProps.interface.ts
  src/templates/ber/interfaces/@props/berReserveJoinHookprops.interface.ts
  src/templates/ber/interfaces/@props/berReserveListProps.interface.ts
  src/templates/ber/interfaces/@props/berReserveMapProps.interface.ts
  src/templates/ber/interfaces/@props/berReserveStudentListProps.interface.ts
  src/templates/ber/interfaces/berCreateReserveQuery.interface.ts
  src/templates/ber/interfaces/berReserve.interface.ts
  src/templates/ber/interfaces/berReserveQuery.interface.ts
  src/templates/ber/interfaces/index.ts
  src/templates/ber/layouts/ReserveCheckBox.tsx
  src/templates/ber/layouts/ReserveJoinBox.tsx
  src/templates/ber/layouts/ReserveList.tsx
  src/templates/ber/layouts/ReserveMap.tsx
  src/templates/ber/layouts/ReserveNoticeRuleList.tsx
  src/templates/ber/layouts/ReserveStudentList.tsx
  src/templates/ber/layouts/index.tsx
  src/templates/ber/services/api.service.ts
  src/templates/ber/services/mutation.service.ts
  src/templates/ber/services/query.service.ts
  src/templates/calendar/hooks/index.ts
  src/templates/calendar/layouts/CalendarListItem.tsx
  src/templates/calendar/layouts/CalendarPlanAddModal.tsx
  src/templates/calendar/layouts/CalendarPlanWriterInformationModal.tsx
  src/templates/calendar/layouts/index.tsx
  src/templates/home/layouts/BasicMode/HomeCalendar.tsx
  src/templates/home/layouts/BasicMode/index.tsx
  src/templates/meister/chart/MeisterChart.tsx
  src/templates/reserve/index.tsx
  src/templates/reserve/layouts/ReserveCategories.tsx
  src/templates/reserve/layouts/ReserveJoinBox.tsx
  src/templates/reserve/layouts/ReserveList.tsx
  src/templates/reserve/layouts/ReserveListItem.tsx
  src/templates/reserve/layouts/ReserveMap.tsx
  src/templates/reserve/services/api.service.ts
Labels: refactor

#115 리팩토링으로 생긴 import 에러 주석 처리
  src/hooks/useTimetableBar.ts
  src/templates/forum-edit/layouts/InputBox.tsx
  src/templates/forum-edit/services/mutation.service.ts
  src/templates/forum-edit/services/query.service.ts
  src/templates/forum-post/layouts/Post.tsx
  src/templates/forum-post/layouts/PostBody/Comment/CommentListItem.tsx
  src/templates/forum-post/layouts/PostBody/CountBox.tsx
  src/templates/forum-post/layouts/PostBody/Recomment/RecommentListItem.tsx
  src/templates/forum-post/layouts/PostBody/SectionBox.tsx
  src/templates/forum-post/layouts/PostHead/PostTitle.tsx
  src/templates/forum-post/layouts/PostHead/ReactBox.tsx
  src/templates/forum-post/services/mutation.service.ts
  src/templates/forum-post/services/query.service.ts
  src/templates/forum-write/layouts/InputBox.tsx
  src/templates/forum-write/services/mutation.service.ts
  src/templates/timetable/layouts/TimeTableBar.tsx
  src/templates/timetable/layouts/TimeTableBox.tsx
  src/templates/timetable/layouts/TimeTableTable.tsx
Labels: refactor

#118 마이스터 페이지 리팩토링
  src/app/meister/page.tsx
  src/components/Flex/Row.tsx
  src/components/Flex/type.ts
  src/components/common/Header/assets/data/navigationList.ts
  src/components/common/Modal/SettingModal/SettingHeader.tsx
  src/hooks/useMeister.ts
  src/provider/layoutProvider.helper.tsx
  src/store/meister.store.ts
  src/store/searchStudentNumber.store.ts
  src/templates/meister/assets/data/graphColorData.ts
  src/templates/meister/assets/data/index.ts
  src/templates/meister/assets/data/meisterChartData.ts
  src/templates/meister/assets/data/meisterDefaultData.ts
  src/templates/meister/assets/data/meisterDetailDefaultData.ts
  src/templates/meister/assets/data/meisterListData.ts
  src/templates/meister/assets/data/meisterVariables.ts
  src/templates/meister/assets/data/radarChartVariables.ts
  src/templates/meister/chart/MeisterChart.tsx
  src/templates/meister/chart/RadarChart.tsx
  src/templates/meister/constants/index.ts
  src/templates/meister/constants/meister.constant.ts
  src/templates/meister/constants/score.constant.ts
  src/templates/meister/helpers/getStudentInformationHTML.helper.ts
  src/templates/meister/helpers/index.ts
  src/templates/meister/helpers/setMeisterPointNaming.helper.ts
  src/templates/meister/hooks/index.ts
  src/templates/meister/hooks/useMeister.tsx
  src/templates/meister/index.tsx
  src/templates/meister/interfaces/@props/circularProgressBoxProps.interface.ts
  src/templates/meister/interfaces/index.ts
  src/templates/meister/interfaces/meister.interface.ts
  src/templates/meister/interfaces/meisterChartData.interface.ts
  src/templates/meister/interfaces/meisterDetail.interface.ts
  src/templates/meister/layouts/BasicJobSkillCard.tsx
  src/templates/meister/layouts/CircularProgressBox.tsx
  src/templates/meister/layouts/Distribution.tsx
  src/templates/meister/layouts/MeisterProfileBox.tsx
  src/templates/meister/layouts/PointHTMLContent.tsx
  src/templates/meister/layouts/Ranking.tsx
  src/templates/meister/layouts/RankingListItem.tsx
  src/templates/meister/layouts/ScoreHTMLContent.tsx
  src/templates/meister/layouts/YearlyMeisterScore.tsx
  src/templates/meister/layouts/index.tsx
  src/templates/meister/services/query.service.ts
  src/templates/meister/types/index.ts
  src/templates/meister/types/meisterKey.type.ts
  src/templates/meister/types/meisterScore.type.ts
Labels: refactor
