Repository Team-INSERT/bssm-frontend, pull requests merged in 2023-07, with the labels that each got.

#20 사이드바 padding에 중복 지정해버린 오류 수정
  src/components/Aside/InfomationBox.tsx
Labels: bug

#21 사이드바 UI/UX 개선
  src/components/Aside/InfomationBox.tsx
  src/components/Aside/JoinCheckBox.tsx
  src/components/Aside/MeisterBox.tsx
Labels: refactor

#22 게시판 퍼블리싱, pages 디렉터리명 변경
  .vscode/settings.json
  package.json
  src/apis/httpClient/index.ts
  src/apis/interceptor/index.ts
  src/app/forum/page.tsx
  src/app/page.tsx
  src/components/Aside/JoinCheckBox.tsx
  src/components/Aside/MeisterBox.tsx
  src/components/Aside/index.tsx
  src/page/forum/adaptors/index.tsx
  src/page/forum/assets/like.svg
  src/page/forum/index.tsx
  src/page/forum/layouts/Categories.tsx
  src/page/forum/layouts/Forum.tsx
  src/page/forum/layouts/ForumFilter.tsx
  src/page/forum/layouts/PostList.tsx
  src/page/forum/layouts/PostListItem.tsx
  src/page/forum/services/.gitkeep
  src/page/home/adaptors/.gitkeep
  src/page/home/assets/.gitkeep
  src/page/home/index.tsx
  src/page/home/services/.gitkeep
  src/pages/meister/adaptors/.gitkeep
  src/pages/meister/assets/.gitkeep
  src/pages/meister/layouts/.gitkeep
  src/pages/meister/services/.gitkeep
  src/utils/constants/exception.constant.ts
  src/utils/constants/forum.constant.ts
  src/utils/constants/service.constant.ts
  yarn.lock
Labels: enhancement

#27 Refactor/recoil
  src/page/forum/layouts/Categories.tsx
  src/page/forum/layouts/ForumFilter.tsx
  src/store/categories.store.ts
  src/store/forumType.store.ts
Labels: enhancement, refactor

#28 일정표 페이지 퍼블리싱
  src/app/schedule/page.tsx
  src/page/schedule/index.tsx
  src/page/schedule/layouts/CalenderList.tsx
  src/page/schedule/layouts/CalenderListItem.tsx
  src/page/schedule/layouts/DateBox.tsx
  src/page/schedule/layouts/ScheduleBox.tsx
  src/page/schedule/layouts/WeekBox.tsx
Labels: enhancement

#31 세부 글 페이지 퍼블리싱
  next.config.js
  src/app/forum/page.tsx
  src/app/page.tsx
  src/app/post/[postType]/[id]/page.tsx
  src/app/schedule/page.tsx
  src/components/Aside/JoinCheckBox.tsx
  src/components/Icon/index.tsx
  src/page/forum/assets/LikeLogo.tsx
  src/page/forum/assets/like.svg
  src/page/forum/layouts/PostListItem.tsx
  src/page/post/assets/CategoryArrow.tsx
  src/page/post/assets/Check.tsx
  src/page/post/assets/CommentIcon.tsx
  src/page/post/assets/Emoji.tsx
  src/page/post/assets/Like.tsx
  src/page/post/assets/Time.tsx
  src/page/post/assets/View.tsx
  src/page/post/index.tsx
  src/page/post/layouts/Post.tsx
  src/page/post/layouts/PostBody/AnonymousBox.tsx
  src/page/post/layouts/PostBody/CommentBox.tsx
  src/page/post/layouts/PostBody/CountBox.tsx
  src/page/post/layouts/PostBody/index.tsx
  src/page/post/layouts/PostHead/Category.tsx
  src/page/post/layouts/PostHead/PostTitle.tsx
  src/page/post/layouts/PostHead/ReactBox.tsx
  src/page/post/layouts/PostHead/index.tsx
  src/styles/globals.css
  src/types/SVGAttribute.ts
Labels: enhancement, refactor

#32 서비스 목록 페이지 퍼블리싱
  src/app/applications/page.tsx
  src/page/applications/assets/LinkArrow.svg
  src/page/applications/index.tsx
  src/page/applications/layouts/AppList.tsx
  src/page/applications/layouts/AppListFilter.tsx
  src/page/applications/layouts/AppListItem.tsx
  src/utils/constants/applications.constant.ts
Labels: enhancement

#33 refactor(convention): global 디렉터리 생성
  src/apis/interceptor/index.ts
  src/app/layout.tsx
  src/components/Aside/MeisterBox.tsx
  src/global/constants/exception.constant.ts
  src/global/constants/service.constant.ts
  src/global/helpers/provider.helper.tsx
  src/global/helpers/reactQueryProvider.helper.tsx
  src/global/types/SVGAttribute.ts
  src/page/applications/constants/applications.constant.ts
  src/page/applications/layouts/AppListFilter.tsx
  src/page/forum/assets/LikeLogo.tsx
  src/page/forum/constants/forum.constant.ts
  src/page/forum/layouts/Categories.tsx
  src/page/forum/layouts/ForumFilter.tsx
  src/page/post/assets/CategoryArrow.tsx
  src/page/post/assets/Check.tsx
  src/page/post/assets/CommentIcon.tsx
  src/page/post/assets/Emoji.tsx
  src/page/post/assets/Like.tsx
  src/page/post/assets/Time.tsx
  src/page/post/assets/View.tsx
  src/store/categories.store.ts
  src/store/forumType.store.ts
Labels: refactor

#35 분실물 찾기 페이지들 퍼블리싱
  src/app/lostfound/[postType]/[id]/page.tsx
  src/app/lostfound/page.tsx
  src/app/lostfound/write/page.tsx
  src/app/post/[postType]/[id]/page.tsx
  src/app/post/write/page.tsx
  src/components/atoms/AnonymousBox.tsx
  src/components/atoms/Category.tsx
  src/components/atoms/CustomEditor.tsx
  src/components/atoms/ImageWithFallback.tsx
  src/components/atoms/Input.tsx
  src/page/forum-post/assets/CategoryArrow.tsx
  src/page/forum-post/assets/Check.tsx
  src/page/forum-post/assets/CommentIcon.tsx
  src/page/forum-post/assets/Emoji.tsx
  src/page/forum-post/assets/Like.tsx
  src/page/forum-post/assets/Time.tsx
  src/page/forum-post/assets/View.tsx
  src/page/forum-post/index.tsx
  src/page/forum-post/layouts/Post.tsx
  src/page/forum-post/layouts/PostBody/CommentBox.tsx
  src/page/forum-post/layouts/PostBody/CountBox.tsx
  src/page/forum-post/layouts/PostBody/index.tsx
  src/page/forum-post/layouts/PostHead/Category.tsx
  src/page/forum-post/layouts/PostHead/PostTitle.tsx
  src/page/forum-post/layouts/PostHead/ReactBox.tsx
  src/page/forum-post/layouts/PostHead/index.tsx
  src/page/forum-write/index.tsx
  src/page/forum-write/layouts/InputBox.tsx
  src/page/forum-write/layouts/WriteBox.tsx
  src/page/lostfound-post/index.tsx
  src/page/lostfound-post/layouts/LostFoundBody/CommentBox.tsx
  src/page/lostfound-post/layouts/LostFoundBody/LostFoundInfoBox.tsx
  src/page/lostfound-post/layouts/LostFoundBody/index.tsx
  src/page/lostfound-post/layouts/LostFoundHead/Category.tsx
  src/page/lostfound-post/layouts/LostFoundHead/LostFoundTitle.tsx
  src/page/lostfound-post/layouts/LostFoundHead/index.tsx
  src/page/lostfound-post/layouts/LostFoundPostBox.tsx
  src/page/lostfound-write/index.tsx
  src/page/lostfound-write/layouts/InputBox.tsx
  src/page/lostfound-write/layouts/StateBox.tsx
  src/page/lostfound-write/layouts/WriteBox.tsx
  src/page/lostfound/assets/imageNotFound.png
  src/page/lostfound/constants/lostfound.constant.ts
  src/page/lostfound/index.tsx
  src/page/lostfound/layouts/LostFoundBox.tsx
  src/page/lostfound/layouts/LostFoundFIlter.tsx
  src/page/lostfound/layouts/LostFoundList.tsx
  src/page/lostfound/layouts/LostFoundListItem.tsx
  src/page/lostfound/layouts/States.tsx
  src/styles/color.ts
Labels: enhancement

#39 이전 PR 코드 리뷰 반영 ( merge 오류 )
  src/apis/error/throwAxiosError.ts
  src/components/atoms/ImageWithFallback.tsx
  src/components/atoms/Select.tsx
  src/components/common/Header/index.tsx
  src/global/assets/svgs/Arrow.tsx
  src/global/assets/svgs/Logo.tsx
  src/global/helpers/getProfileUrl.helper.ts
  src/global/types/SVGAttribute.type.ts
  src/hooks/useUser.ts
  src/page/applications/assets/LinkArrow.tsx
  src/page/forum-post/assets/CategoryArrow.tsx
  src/page/forum-post/assets/Check.tsx
  src/page/forum-post/assets/CommentIcon.tsx
  src/page/forum-post/assets/Emoji.tsx
  src/page/forum-post/assets/Like.tsx
  src/page/forum-post/assets/Time.tsx
  src/page/forum-post/assets/View.tsx
  src/page/forum/assets/LikeLogo.tsx
  src/page/lostfound-post/layouts/LostFoundBody/index.tsx
  src/page/timetable/layouts/TimteTableBox.tsx
  src/store/user.store.ts
Labels: refactor

#40 급식표 페이지 퍼블리싱
  package.json
  src/app/meal/page.tsx
  src/components/Icon/index.tsx
  src/components/atoms/AnonymousBox.tsx
  src/global/assets/svgs/Check.tsx
  src/page/meal/assets/.gitkeep
  src/page/meal/constants/meal.constant.ts
  src/page/meal/index.tsx
  src/page/meal/layouts/ListSlider.tsx
  src/page/meal/layouts/Meal.tsx
  src/page/meal/layouts/MealListItem.tsx
  src/page/meal/layouts/SwipeArea.tsx
  src/page/meal/type/mealList.type.ts
  src/page/meal/type/mealListItem.type.ts
  src/styles/color.ts
  yarn.lock
Labels: enhancement

#42 모달 컴포넌트, state 및 hook 세팅
  src/components/common/Header/index.tsx
  src/components/common/Modal/SettingModal/index.tsx
  src/components/common/Modal/View.tsx
  src/components/common/Modal/index.tsx
  src/global/assets/svgs/Setting.tsx
  src/global/helpers/provider.helper.tsx
  src/global/types/modal.type.ts
  src/hooks/useModal.ts
  src/hooks/useUser.ts
  src/store/modal.store.ts
Labels: enhancement, refactor
